---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mesure-impact-sante-basavi-tokens
  namespace: mesure-impact-dev
spec:
  encryptedData:
    GRIST_API_KEY: AgCMi9b1T655SMxvCAWC0w4AEdCQcSDZRIuysLBLGvC6wUlWmAn/0Xof6Y7BvyqcDkQzXQyIr32BxwhCSVtgzEHNiIjcxbJPEJ3ig6QHUxIM3KsliJ9jdjbO/fCBRtKrFRShj6+wbIS7FLeaC9IulNUdls+z2ckGACKG2ZDQuPUH6Fo545w+pg/ics+XsXj+JnOJJL2oTgLepUHj9Wq0mIfG9hJP8PgvXN/b4GAdGyCyDPAha4plv5cPv6lnj6uzA1Y4cCuZOKf23JUTstkHQl8c7cdwJpesrGwmRJqwRrUIlybqGzmeM4WSbai3aW8yOueQE65POcfuPxeMAIYMMPfi7utihRrdrm9A5avYmpYOcLhh2RbxsHnsmT++8cxgJ1ndklLIyfyEduWiClrK6cBW5fODRxlhwSYmg06XRZnaeqCy+iw8ejOuajtm4rsLu3LlnBvXMr8K/8Rfa/Fyvi7fWQKOFXwXiZ8ttlk6xkAVIDNwf6SHOR9nTVI5k75YZIVneBg+718FKj2jlyxrwtzMRfZUpGTT2zKh4rjbuaoUpZJtG74I39Uk1nwcXLF45Gdueecd+GXAY5987bInOjuAdn91OzCAORMVTR26iao+oHUeKt80Z3KLtjXawoGspZtkJ9RSroLB/rF65pynAm32YN8oKcRi/2roUFKWGKoIrDwjVF/9Majl81x0qCqkEMMhCrQRE2RVgzX/dBRw7nZ+AbTTEytHSuTLRypqiS4bSfCX7T2YJEMk
    MATOMO_TOKEN_AUTH: AgC9kPh+KEM4hFYH8xwS6JHu9i1Wx28qkaxMzZoIIqYCJY/TN49LHUxethCjbs/vNi70Io6EIQHzh2BRcMfcXFynUwdTY6NCmZQ0XW2oRfZ3dSQj7a8niQDzmd4P3ph2Vel/okJK264w2LYT3Hs44Z+kEyudYVOKudasvBNA8FOH/Lt//1cnJ3FGOqx+KKVpeepi3uz7av6ZsqXm2x92UXLySy+Mn8x82kPFmuz1OgJ8QAqQX2+Np917aA5VR/b5QOJ0tT26BMo+MfNiF6qu4uJqEFfObwM6L3YdVX9Lhor14+oCcKJsLAYbGrGppqJ741PD9zhUB61BwqvAom1Hh0dkyfbZ6NfH5mtlXIUihvpCWo/Rk64KzeulqTB2soA3duOmv2V5xK8cgOyvrsKLI1fwwG3TVdJR12vHXxOzXbc3Rb1gyWPM2uOC+KSFtzLHH1gXxHGQD/988lEk1bokRlt9NZoAWfk9vdW+TvYgTNWapzp2qoke1CJj0a/tWxtNcZMj+/cCqOEQ2NfUvLDbqPzjtWCGvvwFcqmLVve5qBMwFjMF1PJqyBl50GudyxahuLfcUsMH7SqC+Sig5GkDwBkw0CQF5vNTg2yvk2z2jXUSvIBPylEF7ILZcvXGT7Mr8WyQXHEaPQm6qhZEiRoSwxZSS5NRT9lLnAMi5su7DCRsvUkO/TsCLxSsZP8bno4B14uiM4CFr+7U5Cxik9NTj8etvwy8jJ7ke0rsyr8F8S2GUA==
  template:
    metadata:
      creationTimestamp: null
      name: mesure-impact-sante-basavi-tokens
      namespace: mesure-impact-dev
