---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mesure-impact-sante-basavi-tokens
  namespace: mesure-impact-prod
spec:
  encryptedData:
    GRIST_API_KEY: AgC6VZzxwgiJLrech/+090gRKw6WHEHRC6W/RLDcaHHLze7LhgDVifcRLpetvwG3NiPAXP9+DUQ5xb/iqEzgqR7gm1yWd7nvg4rirwyryNqdf5Wv8WQL+g8XC9YElWc/xSVrLp1kzTJ+KnWTHh3RXL2aPrFPPO7y8ax5KHSZW7liRZk2Y2O5eQgddC+8mnChyi3C4I3sClOS00GFZlYNPHQG39DdROcNaSej4zGu4L3g2ITZrJ//uZZnKBw2R7n1lN3LhLQP7TKtAHHLyuajUvNGdEDlK1e80gAk+fnGtrQvFtNsm7Y28M/6bdvvSE6aCP2GaiMy2orahmN3TFkTlXGJd5XdEf1xXZL9aG8hWf9CSOW1aLuUnurD8Nm0+oOnPjkT37xlGeQo66eVDDoFt0AKnSThchTR8AyRtKhtS8VoIzvvS+hGsykHqTtt5mAm+dSRNfOBIl3c6vR22WHOeTqfY6KfVx9RHlyT6TeWA9nqCf2uEnZai/3E3nvsO/xXO4HmmkSnSYtaMVIljodUPNd5cXtlXbV+ujaNkcEbT9iBMvEqLJ/msm+3ouo0F44qUr3w6bM2GBg3iCgD8uXpOdE7Y3oDWhfoM4iXggXzaksU+NapoI9ge7DD4z6xhnD++eaGVWldnaaQxduxcCeXgnJZy0IDtyF1A5yqSx9flX3J0/V31WF3A9PAMqZjjcUg/8RTMBH6I3xPvvtqvBBNRxKCEOFZrD7kdD+n1wE8yJUMvWjFccRhRAgh
    MATOMO_TOKEN_AUTH: AgBe40lq78jS3VoX+0W73Nbj4xkVWas9g3EKDQlNN9mppeBzB/uh5kcoCmzBUNBbOaW03qwORsTF2ZB4z2WwLioCqDkSJeIPvQFOJ1j7bLAT5q2ky2559dDSe00KyRP9Ce1A4fXb/GxcuysqjPPuV3JRdLjHttw5HBmVp4D6OQiN0CFU1OAsamvR52gq81eIYK8wf4sGEx6wdBPzxEN8o5jcbYMTGHBofvRWsU/xXP5H5p6WannAxpj30wo2OdpMXpqb3EQFh7p6ZBr3qvAC46ojl3nkbZqoOOzoKDLTJTxBK/nwFRpX63SprGXVsyX1ZwK7DawarFuLA2cSR6GUgSqOyxhA6hZEdqEBteWl8HHGqkHTpAT6WOW9t0geTr/XopCiJuGLp7WOq/kx3TGMxwtY+gMN4/B2gmTK2ovp3p18bAEUWk1IUy/Nd7EhEBMWWv156b+Wa+qMlGe5jAIRn20zfNyQJUiwUEGTqsxVMO11gH3XkO4CfOn3tCdk7vJCKBgxFeXqY2d77aowZ4BdvriD9cLaB96VlOxFFVDOtVescg96nsE5pPcbGXdcYmEYEBqa10Y+wFwp1rkstCY0hW9Nckl9j8CQwVvfcvKQxKtbHTJe2abqavTBcoMrXiGlRxn/eteljB7O3AfXhAT7c9fwUJYgGd+K/d6T9WHTiJnGwUzOLxj+tTiWAmWBl/SiaXh2p7zYqU13PI927ztk3EXVnhsy2SgknKTuq/5gDtzCGw==
  template:
    metadata:
      creationTimestamp: null
      name: mesure-impact-sante-basavi-tokens
      namespace: mesure-impact-prod
