environment: dev

web:
  host: mesure-impact-dev.ovh.fabrique.social.gouv.fr

cron:
  # Tokens scellés le 20/08/2026 (envs/dev/sealed-secrets/tokens.sealedsecret.yaml).
  suspend: false
  schedule: "0 6 * * *"
